[theme]

# Primary accent for interactive elements
primaryColor = '#CF4ED5'

# Background color for the main content area
backgroundColor = '#0D1117'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#CF4ED5'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"